name: FRONT-API

on: push

jobs:
  test:
    name: API Test 
    runs-on: ubuntu-latest

    steps:
    - name: CLONAR ARQUIVOS DE REPOSITORIO
      uses: actions/checkout@v4

    - name: CONFIGURAR PYTHON
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: INSTALAÇÃO DAS DEPENDENCIAS
      run: |
        pip install robotframework
        pip install robotframework-requests
        pip install Faker
        pip install robotframework-seleniumlibrary

    - name: EXECUTANDO OS TESTES DE API DO ROBOT
      run: |
        robot --outputdir results/ test/ test/company/
      
    - name: TEST REPORT
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: robot-framework-report
        path: results

  deploy:
    name: Deploy GitHub Pages 🌐
    runs-on: ubuntu-latest
    needs: 
      - test

    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages           
      url: https://wayslan-in.github.io/WAYSLAN-TESTE-DE-API-COM-ROBOT/report.html    

    steps:
      - name: SETUP PAGES
        uses: actions/configure-pages@v2

      - name: DOWNLOAD ARTIFACTS
        uses: actions/download-artifact@v4
        with: 
          name: robot-framework-report
          path: results/

      - name: UPLOAD ARTIFACT
        uses: actions/upload-pages-artifact@v1
        with:
          path: results/

      - name: DEPLOY TO GITHUB PAGES
        uses: actions/deploy-pages@v1

